### ISSUE TITLE
remove adopter connection from config file

### ISSUE THREAD

**Issue by emmanuelbuah** [okv/east#14]
Putting the  adopter connection string in the config file make it hard to run migration for different environments. It also make it so you connection is in your source code. The best way is to abstract that out so the user can pass that in at run time.

**Comment by okv** [comment]
Adapter and other config options can be overridden at run time - you can pass it to east cli or to migrator constructor (if using it from code).

**Comment by emmanuelbuah** [comment]
Can you provide code example on how to do that?

**Comment by okv** [comment]
e.g. fot cli:

```sh
bin/east --adapter lib/adapter.js list
```

from code:

```js
var Migrator = require('east/lib/migrator');

var migrator = new Migrator({
    config: 'path/to/config',
    adapter: 'lib/adapter.js',
    ....
});

migrator.connect(....
```
