### ISSUE TITLE
Rollback or forward depending on current migration state

### ISSUE THREAD

**Issue by emmanuelbuah** [okv/east#16]
If I execute migration 1 when the current migration state is at 3, it should rollback to 1. That reduces the api need for any migration as well as making it easy to just target a particular migration state without worry if it's a forward or backward migration.  

Thus, if the current state is 3, executing the shell below will rollback to 1. Currently, it tries to run and only 1 again. 
`` 
east migrate 1
``

**Comment by okv** [comment]
Hi.
Currently there is no such strict thing as state e.g. you can have 3 migrations, but only third is executed (e.g. by `east migrate 3`). So the general thing is that you just migrate or rollback selected (or all executed/unexecuted) migration files. That's just simple and I don't plan to change that.
From my point of view on cli level some command which combines `migrate` and `rollback` commands may exist. But currently I'm not ready to talk about particular implementation. 
If you really need such behavior you can implement it using east programmatic api (Migrator class which will be documented and exposed explicitly from library but could be used even now, see examples at issues #14).
