### ISSUE TITLE
markStarted in addition to markExecuted

### ISSUE THREAD

**Issue by mmiller42** [okv/east#28]
If a migration takes a long time, in a system with multiple containers, more than one node process might execute the same migration. It would be useful to "lock" the migration when it is started and release the lock on resolution/failure.

**Comment by okv** [comment]
Sounds like good feature) But I have some concerns about releasing lock (especially on failure). I need to think carefully about that.

**Comment by okv** [comment]
I thought about it, seems like there is no way to implement this feature without changing adapters api. Such feature may also involve some not simple logic with bunch of options - e.g. different actions can be taken (throw an error; skip migration; wait until migration end and so on) in current process when migration is executing in another.

As possible solution - implement this as a [plugin](https://github.com/okv/east#plugins) which stores information about executing migration in some lightweight store (e.g. redis) or even uses some key/value abstraction (e.g. [keyv](https://github.com/lukechilds/keyv)) for that.

I'm closing this issue, but feel free to share your feedback at any time.
