### ISSUE TITLE
Created east-mysql package

### ISSUE THREAD

**Issue by riggerthegeek** [okv/east#6]
Not a problem as such, but I've created the east-mysql package that I promised I would.  You can find it at https://github.com/riggerthegeek/east-mysql

**Comment by okv** [comment]
Good job, i'll add link to the adapter on east page.
But `markExecuted` method should allow mark of already marked transaction to support `migrate --force`. I've just added test for that to the east repository.

**Comment by riggerthegeek** [comment]
Ok.  I'll update the package this week and create a new version - I'll create an issue on the package
