### ISSUE TITLE
link to couchdb adapter

### ISSUE THREAD

**Issue by schipiga** [okv/east#63]
Hello!

I implemented adapter for couchdb: https://github.com/schipiga/east-couchdb. Could you pls add to your readme as well.

**Comment by okv** [comment]
Hi, nice job in general :+1: 
But there seems to be some problems, east adapter test suite is not passed.
My setup is:

At cloned repository I have `.eastrc`:

```json
{
	"adapter": "../east-couchdb/",
	"couchdb": {
		"host": "127.0.0.1",
		"port": 5984,
		"username": "admin",
		"password": "admin"
	}
}
```

then I run tests:

```
NODE_EAST_TEST_LOAD_CONFIG=1 npm run testSpecified test/01-migrator
```

and got an error:

```
test/01-migrator/create/withDateTimeMigrationNumberFormat.js
  migrator create with date time migration number format
    # Subtest:
      1) Database does not exist.
      2) test count !== plan
      3) test count !== plan
```
At first look of adapters code I should say that database should be created at `connect` method not at `getExecutedMigrationNames`. Please test the adapter against that test suite and fix the issues.

**Comment by schipiga** [comment]
Hi @okv! Thank you for response. I moved database creation into `connect()` and even added double check in db creation:
```js
    if (!(await this._conn.db.list()).includes(this._dbName)) {
        try {
            await this._conn.db.create(this._dbName);
        } catch (e) {
            if (!(await this._conn.db.list()).includes(this._dbName)) {
                throw e;
            }
        }
    }
```
Nevertheless tests were failed in random places. The root cause is tests are launched in parallel with flag `--jobs-auto` which leads to race condition in random places. With flag `--jobs 1` it works well.
I suppose tests, like a migrations, should happen sequentially step-by-step with one thread (process). And it's expected that no other processes manage migration table.

**Comment by okv** [comment]
Definitely adapters tests should be run in one thread, nice catch!
I updated this instructions in readme.
I also added link to couchdb adapter to readme.
