### ISSUE TITLE
Support interleaved tagged migrations or multiple tags

### ISSUE THREAD

**Issue by jayhogan** [okv/east#9]
I'm trying to using the tag feature to support loading test data for automated functional and performance tests. However, I cannot figure out how to run the migrations so that the test data migrations are executed in the intended order. I tried adding a TEST tag to the test data migrations and running `east migrate -t TEST` but only the TEST migrations are run. Then I tried giving every migration the ALL tag except the test data migrations and executed the migrations by specifying multiple tags, like so: `east migrate -t ALL,TEST`, which did not work. I tried various ways of specifying multiple tags but nothing seemed to work.

Is there a way to use the tags feature to ensure that the tagged migrations are executed with untagged (or alternately tagged) migrations in the correct order? In other migration frameworks, notably [Liquibase](http://www.liquibase.org/), running the migrate command with a tag argument executes the migrations marked with the tag, as well as any untagged migrations.

**Comment by okv** [comment]
I see your problem. Currently tag is just a filter for migrations to run and you can set only one tag.
I'm going to implement tag option as an expression (something with logic AND, OR, NOT conditions) but it still will be just a filter and will not have any impact on migrations order. Does such implementation fit to your needs?

**Comment by jayhogan** [comment]
Sorry for the late response No, I don't think that will work for me as I need to ensure that the migrations execute in order. I think I'm just going to solve for this by setting an environment variable when running running the migration, i.e. `TAGS='TEST' east migrate` then checking that the expected TAG is present when creating targeted migrations using `process.env.TAGS`. I am going to need a custom adapter for my use case anyway as east-mongo does not currently support authenticating against an admin database so I will add some helpers there to make this less painful for my devs.

If I get it working and it looks like it may be useful to others I will submit a PR. Thank!
